name: 'Pytest run'
description: 'Run tests'
inputs:
  python-version:  # id of input
    description: 'Python version to use'
    required: true
  redis:
    description: 'Redis version'
    required: true
  codecov_token:
    description: Codecov Token
    required: true
runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v3
    with:
      python-version: ${{ inputs.python-version }}
  - name: Cache Redis builds
    uses: actions/cache@v3
    with:
      path: ~/redis
      key: redis-${{ hashFiles('.download-redis.sh') }}
  - name: Get pip cache dir
    id: pip-cache
    shell: bash
    run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
  - name: pip cache
    uses: actions/cache@v3
    with:
      path: ${{ steps.pip-cache.outputs.dir }}
      key: pip-${{ inputs.python-version }}-${{ hashFiles('requirements-*.txt') }}
      restore-keys: |
        pip-${{ matrix.python-version }}-
  - name: Run test on Redis ${{ inputs.redis }}
    uses: fizyk/actions-reuse/.github/actions/pipenv@v1.7.1
    with:
      python-version: ${{ matrix.python-version }}
      command: pytest -n 0 --cov-report=xml --redis-exec=$HOME/redis/redis-${{ inputs.redis }}/src/redis-server
  - name: Run xdist test on Redis ${{ inputs.redis }}
    uses: fizyk/actions-reuse/.github/actions/pipenv@v1.7.1
    with:
      python-version: ${{ matrix.python-version }}
      command: pytest -n 1 --cov-report=xml:coverage-xdist.xml --redis-exec=$HOME/redis/redis-${{ inputs.redis }}/src/redis-server
  - name: Upload coverage to Codecov
    uses: codecov/codecov-action@v3.0.0
    with:
      flags: linux,redis-${{ inputs.redis }}
      env_vars: OS, PYTHON
      fail_ci_if_error: false
      token: ${{ inputs.codecov_token }}